---

version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.aws/credentials:/root/.aws/credentials:ro
    environment:
      - PYTHONUNBUFFERED=1
      - BASE_IMAGE_TAG=3.12-slim
      - DOCKER_ENV_VARS='on'
