name: Pytests

on:
  pull_request:
  push:
    branches: [ JOSS ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.11']
        include:
          - os: ubuntu-latest
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
        fetch-tags: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest
        python -m pip install requests
        python -m pip install -e .
    - name: Run pytest
      run: |
        python -m pytest -v --disable-warnings
